id: IB4BC65BA
legacy_id: P010319
ocr_import_info:
  bdrc_scan_id: W00EGS1016695
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T15:04:46'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T11:02:57.550342+00:00'
last_modified: 2022-08-30 19:03:47.623652
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1016695
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1016695
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཁང་གསར་སྐྱབས་མགོན་བློ་བཟང་ཚུལ་ཁྲིམས་བསྟན་པའི་རྒྱལ་མཚན་གྱི་རྣམ་ཐར།
  author: ཁྲི ༩༠་བྱམས་པ་ཆོས་གྲགས།
statistics:
  ocr_word_mean_confidence_index: 0.9580340310335922
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I01JW74:
    source_metadata:
      id: http://purl.bdrc.io/resource/I01JW74
      total_pages: 305
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I01JW74.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9580340310335922
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
