id: IB4BC65BA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T15:06:50+00:00'
last_modified: '2022-06-08T12:43:02.131683+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1016695
  title: ཁང་གསར་སྐྱབས་མགོན་བློ་བཟང་ཚུལ་ཁྲིམས་བསྟན་པའི་རྒྱལ་མཚན་གྱི་རྣམ་ཐར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9BBA:
      image_group_id: I01JW74
      title: ''
      total_pages: 305
      order: 1
      base_file: 9BBA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
